// Auto-generated by scripts/build.py — edit data/*.yaml instead.

const CONFERENCES = [
  {
    "title": "Adopting Bitcoin — South Africa",
    "link": "https://za25.adoptingbitcoin.org/",
    "date": "2025-01-24",
    "location": "Cape Town",
    "flag": "🇿🇦"
  },
  {
    "title": "Plan B Forum — El Salvador",
    "link": "https://planb.sv/",
    "date": "2025-01-30",
    "location": "El Salvador",
    "flag": "🇸🇻"
  },
  {
    "title": "Sats N'Facts",
    "link": "https://satsnfacts.btc.pub/",
    "date": "2025-02-08",
    "location": "Chiang Mai",
    "flag": "🇹🇭"
  },
  {
    "title": "bitcoin++ hacking edition",
    "link": "https://btcplusplus.dev/conf/floripa",
    "date": "2025-02-19",
    "location": "Florianópolis",
    "flag": "🇧🇷"
  },
  {
    "title": "Bitcoin Alive",
    "link": "https://bitcoinalive.io/",
    "date": "2025-03-08",
    "location": "Sydney",
    "flag": "🇦🇺"
  },
  {
    "title": "BitBlockBoom",
    "link": "https://bitblockboom.com",
    "date": "2025-04-03",
    "location": "Dallas",
    "flag": "🇺🇸"
  },
  {
    "title": "MIT Bitcoin Expo",
    "link": "https://mitbtcexpo.org/",
    "date": "2025-04-05",
    "location": "Cambridge",
    "flag": "🇺🇸"
  },
  {
    "title": "OP_NEXT",
    "link": "https://opnext.dev/",
    "date": "2025-04-11",
    "location": "Tysons",
    "flag": "🇺🇸"
  },
  {
    "title": "bitcoin++ mempool edition",
    "link": "https://btcplusplus.dev/conf/atx25",
    "date": "2025-05-07",
    "location": "Austin",
    "flag": "🇺🇸"
  },
  {
    "title": "Bitcoin Ireland",
    "link": "https://bitcoinireland.eu/",
    "date": "2025-05-24",
    "location": "Dublin",
    "flag": "🇮🇪"
  },
  {
    "title": "Bitcoin 2025",
    "link": "https://b.tc/conference/2025",
    "date": "2025-05-27",
    "location": "Las Vegas",
    "flag": "🇺🇸"
  },
  {
    "title": "Bitcoin Seoul",
    "link": "https://bitcoinseoul.kr/en",
    "date": "2025-06-04",
    "location": "Seoul",
    "flag": "🇰🇷"
  },
  {
    "title": "BTC Prague 2025",
    "link": "https://btcprague.com",
    "date": "2025-06-19",
    "location": "Prague",
    "flag": "🇨🇿"
  },
  {
    "title": "Bitcoin Rodeo",
    "link": "https://bitcoinrodeo.com/",
    "date": "2025-06-28",
    "location": "Calgary",
    "flag": "🇨🇦"
  },
  {
    "title": "Bitcoin Alaska",
    "link": "https://bitcoinalaska.org/",
    "date": "2025-07-01",
    "location": "Juneau",
    "flag": "🇺🇸"
  },
  {
    "title": "Bitcoin is for Everyone",
    "link": "https://bitcoinisforeveryone.com/",
    "date": "2025-08-01",
    "location": "Portland",
    "flag": "🇺🇸"
  },
  {
    "title": "bitcoin++ privacy edition",
    "link": "https://btcplusplus.dev/privacy",
    "date": "2025-08-07",
    "location": "Riga",
    "flag": "🇱🇻"
  },
  {
    "title": "Baltic Honeybadger",
    "link": "https://baltichoneybadger.com/",
    "date": "2025-08-09",
    "location": "Riga",
    "flag": "🇱🇻"
  },
  {
    "title": "BTCHEL",
    "link": "https://btchel.com/",
    "date": "2025-08-15",
    "location": "Helsinki",
    "flag": "🇫🇮"
  },
  {
    "title": "Learning Bitcoin",
    "link": "https://www.learningbitcoin.ca/",
    "date": "2025-08-16",
    "location": "Vancouver",
    "flag": "🇨🇦"
  },
  {
    "title": "The Scottish Bitcoin Conference",
    "link": "https://www.glasgowbitcoin.co.uk",
    "date": "2025-08-23",
    "location": "Glasgow",
    "flag": "🏴󠁧󠁢󠁳󠁣󠁴󠁿"
  },
  {
    "title": "Bitcoin Asia",
    "link": "https://b.tc/conference/asia",
    "date": "2025-08-28",
    "location": "Hong Kong",
    "flag": "🇭🇰"
  },
  {
    "title": "bitcoin++ scaling edition",
    "link": "https://btcplusplus.dev/conf/istanbul",
    "date": "2025-09-03",
    "location": "Istanbul",
    "flag": "🇹🇷"
  },
  {
    "title": "Bitcoin Indonesia",
    "link": "https://bitcoinindonesia.xyz/bitcoin-indonesia-conference-2025",
    "date": "2025-09-05",
    "location": "Bali",
    "flag": "🇮🇩"
  },
  {
    "title": "bitcoin++ lightning edition",
    "link": "https://btcplusplus.dev/conf/berlin25",
    "date": "2025-10-02",
    "location": "Berlin",
    "flag": "🇩🇪"
  },
  {
    "title": "TABConf 7",
    "link": "https://7.tabconf.com",
    "date": "2025-10-13",
    "location": "Atlanta",
    "flag": "🇺🇸"
  },
  {
    "title": "The Canadian Bitcoin Conference",
    "link": "https://canadianbitcoinconf.com/",
    "date": "2025-10-16",
    "location": "Montreal",
    "flag": "🇨🇦"
  },
  {
    "title": "Plan B Forum — Lugano",
    "link": "https://planb.lugano.ch/planb-forum/",
    "date": "2025-10-24",
    "location": "Lugano",
    "flag": "🇨🇭"
  },
  {
    "title": "SatsConf",
    "link": "https://www.satsconf.com.br/2025",
    "date": "2025-11-07",
    "location": "São Paulo",
    "flag": "🇧🇷"
  },
  {
    "title": "Mining Disrupt",
    "link": "https://miningdisrupt.com",
    "date": "2025-11-11",
    "location": "Dallas",
    "flag": "🇺🇸"
  },
  {
    "title": "Adopting Bitcoin — El Salvador",
    "link": "https://sv25.adoptingbitcoin.org/",
    "date": "2025-11-14",
    "location": "San Salvador",
    "flag": "🇸🇻"
  },
  {
    "title": "bitcoin++ goes local",
    "link": "https://btcplusplus.dev/conf/durham",
    "date": "2025-11-15",
    "location": "Durham",
    "flag": "🇺🇸"
  },
  {
    "title": "Africa Bitcoin Conference",
    "link": "https://afrobitcoin.org/",
    "date": "2025-12-03",
    "location": "Mauritius",
    "flag": "🇲🇺"
  },
  {
    "title": "Bitcoin MENA",
    "link": "https://mena.b.tc/",
    "date": "2025-12-08",
    "location": "Abu Dhabi",
    "flag": "🇦🇪"
  },
  {
    "title": "bitcoin++ sovereignty edition",
    "link": "https://btcplusplus.dev/conf/taipei",
    "date": "2025-12-15",
    "location": "Taipei",
    "flag": "🇹🇼"
  },
  {
    "title": "Plan B Forum — El Salvador",
    "link": "https://planb.sv/",
    "date": "2026-01-30",
    "location": "El Salvador",
    "flag": "🇸🇻"
  },
  {
    "title": "Adopting Bitcoin — South Africa",
    "link": "https://za26.adoptingbitcoin.org/",
    "date": "2026-01-30",
    "location": "Cape Town",
    "flag": "🇿🇦"
  },
  {
    "title": "bitcoin++ exploits edition",
    "link": "https://btcplusplus.dev/conf/floripa26",
    "date": "2026-02-26",
    "location": "Florianópolis",
    "flag": "🇧🇷"
  },
  {
    "title": "BitBlockBoom",
    "link": "https://bitblockboom.com",
    "date": "2026-04-09",
    "location": "Dallas",
    "flag": "🇺🇸"
  },
  {
    "title": "MIT Bitcoin Expo",
    "link": "https://mitbitcoinexpo.org/",
    "date": "2026-04-11",
    "location": "Cambridge",
    "flag": "🇺🇸"
  },
  {
    "title": "OP_NEXT",
    "link": "https://opnext.dev/",
    "date": "2026-04-16",
    "location": "New York",
    "flag": "🇺🇸"
  },
  {
    "title": "bitcoin++ villain edition",
    "link": "https://btcplusplus.dev/conf/vegas",
    "date": "2026-04-23",
    "location": "Hoover Dam",
    "flag": "🇺🇸"
  },
  {
    "title": "Bitcoin is for Everyone",
    "link": "https://bitcoinisforeveryone.com/",
    "date": "2026-05-22",
    "location": "Portland",
    "flag": "🇺🇸"
  },
  {
    "title": "Bitcoin Ireland",
    "link": "https://bitcoinireland.eu/",
    "date": "2026-05-22",
    "location": "Dublin",
    "flag": "🇮🇪"
  },
  {
    "title": "bitcoin++ economics edition",
    "link": "https://btcplusplus.dev/conf/vienna",
    "date": "2026-05-27",
    "location": "Vienna, Austria",
    "flag": "🇦🇹"
  },
  {
    "title": "Bitcoin FilmFest 2026",
    "link": "https://bitcoinfilmfest.com/bff26",
    "date": "2026-06-04",
    "location": "Warsaw",
    "flag": "🇵🇱"
  },
  {
    "title": "BTC Prague 2026",
    "link": "https://btcprague.com",
    "date": "2026-06-11",
    "location": "Prague",
    "flag": "🇨🇿"
  },
  {
    "title": "bitcoin++ open source edition",
    "link": "https://btcplusplus.dev/conf/nairobi",
    "date": "2026-06-17",
    "location": "Kenya, Nairobi",
    "flag": "🇰🇪"
  },
  {
    "title": "Bitcoin Nairobi Conference",
    "link": "https://bitcoinnairobiconference.com/",
    "date": "2026-06-24",
    "location": "Nairobi",
    "flag": "🇰🇪"
  },
  {
    "title": "bitcoin++ consensus edition",
    "link": "https://btcplusplus.dev/conf/toronto",
    "date": "2026-07-22",
    "location": "Toronto",
    "flag": "🇨🇦"
  },
  {
    "title": "Learning Bitcoin",
    "link": "https://www.learningbitcoin.ca/",
    "date": "2026-08-22",
    "location": "Vancouver",
    "flag": "🇨🇦"
  },
  {
    "title": "Bitcoin Asia",
    "link": "https://asia.b.tc/",
    "date": "2026-08-27",
    "location": "Hong Kong",
    "flag": "🇭🇰"
  },
  {
    "title": "BTCHEL",
    "link": "https://btchel.com/",
    "date": "2026-09-25",
    "location": "Helsinki",
    "flag": "🇫🇮"
  },
  {
    "title": "bitcoin++ payments edition",
    "link": "https://btcplusplus.dev/conf/berlin26",
    "date": "2026-10-01",
    "location": "Berlin",
    "flag": "🇩🇪"
  },
  {
    "title": "The Canadian Bitcoin Conference",
    "link": "https://canadianbitcoinconf.com/",
    "date": "2026-10-02",
    "location": "Toronto",
    "flag": "🇨🇦"
  },
  {
    "title": "TABConf 8",
    "link": "https://8.tabconf.com",
    "date": "2026-10-12",
    "location": "Atlanta",
    "flag": "🇺🇸"
  },
  {
    "title": "Plan B Forum — Lugano",
    "link": "https://planb.lugano.ch/planb-forum/",
    "date": "2026-10-23",
    "location": "Lugano",
    "flag": "🇨🇭"
  },
  {
    "title": "Bitcoin Alive",
    "link": "https://bitcoinalive.io/",
    "date": "2026-10-31",
    "location": "Sydney",
    "flag": "🇦🇺"
  },
  {
    "title": "Bitcoin Amsterdam",
    "link": "https://www.bitcoin.amsterdam/2026",
    "date": "2026-11-05",
    "location": "Amsterdam",
    "flag": "🇳🇱"
  },
  {
    "title": "Bitcoin Korea Conference",
    "link": "https://www.bitcoinkoreaconference.com/en",
    "date": "2026-11-07",
    "location": "Seoul",
    "flag": "🇰🇷"
  },
  {
    "title": "Africa Bitcoin Conference",
    "link": "https://afrobitcoin.org/",
    "date": "2026-12-02",
    "location": "Blantyre",
    "flag": "🇲🇼"
  },
  {
    "title": "Plan B Forum — El Salvador",
    "link": "https://planb.sv/",
    "date": "2027-01-29",
    "location": "El Salvador",
    "flag": "🇸🇻"
  },
  {
    "title": "Adopting Bitcoin — Cape Town",
    "link": "https://za27.adoptingbitcoin.org/",
    "date": "2027-02-26",
    "location": "Cape Town",
    "flag": "🇿🇦"
  }
];
