#!/usr/bin/env python3
"""Read data/*.yaml and write website/conferences.js."""

import json
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("pyyaml is required: pip install pyyaml")

ROOT = Path(__file__).parent.parent
DATA_DIR = ROOT / "data"
OUTPUT = ROOT / "website" / "conferences.js"


def load():
    conferences = []
    for path in sorted(DATA_DIR.glob("*.yaml")):
        entries = yaml.safe_load(path.read_text(encoding="utf-8"))
        for entry in entries:
            if hasattr(entry["date"], "isoformat"):
                entry["date"] = entry["date"].isoformat()
        conferences.extend(entries)
    return sorted(conferences, key=lambda c: c["date"])


def write(conferences):
    body = json.dumps(conferences, ensure_ascii=False, indent=2)
    OUTPUT.write_text(
        "// Auto-generated by scripts/build.py — edit data/*.yaml instead.\n\n"
        f"const CONFERENCES = {body};\n",
        encoding="utf-8",
    )
    print(f"wrote {len(conferences)} conferences → {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    write(load())
